# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby_desk}
  s.version = "0.9.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ahmed ElDawy"]
  s.date = %q{2011-05-09}
  s.description = %q{A gem that works as an interface for oDesk APIs that can be used for both desktop and web applications}
  s.email = %q{ahmed.eldawy@badrit.com}
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/categories",
    "lib/ruby_desk.rb",
    "lib/ruby_desk/connector.rb",
    "lib/ruby_desk/hrjob.rb",
    "lib/ruby_desk/job.rb",
    "lib/ruby_desk/odesk_entity.rb",
    "lib/ruby_desk/provider.rb",
    "lib/ruby_desk/snapshot.rb",
    "lib/ruby_desk/team_room.rb",
    "lib/ruby_desk/time_report.rb",
    "lib/ruby_desk/user_role.rb",
    "test/empty_timereport.json",
    "test/frob.json",
    "test/helper.rb",
    "test/jobs.json",
    "test/profile.json",
    "test/providers.json",
    "test/snapshot.json",
    "test/teamrooms.json",
    "test/test_ruby_desk.rb",
    "test/timereport.json",
    "test/timereport_error.json",
    "test/workdiary.json"
  ]
  s.homepage = %q{http://github.com/aseldawy/ruby_desk}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Wrapper for oDesk APIs in Ruby}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<json>, [">= 0"])
    else
      s.add_dependency(%q<json>, [">= 0"])
    end
  else
    s.add_dependency(%q<json>, [">= 0"])
  end
end

